version: '3'

serivces:

  compile:
    build: 
      context: .
    volumes:
      - ./war_data/target/:/tmp/

   web:
    image: tomcat
    ports:
      -'8081:8080'
    volumes:
      - ./war_data/target/*.war:/usr/local/tomcat/webapps/*.war
     depends_on:
      - compile
