---
- hosts: build-host
  vars:
    packages-build-host: 
      - git
      - default-jdk
      - maven
    app_dir: /root/project
    repo_url: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
  become: yes
  tasks:
  - name: install packages-build-host
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    with_items:
      "{{packages-build-host}}"
  - name: clone pom.xml
    git:
      repo: "{{repo_url}}"
      dest: "{{app_dir}}"
      clone: yes
  - name: build war app
    shell: mvn package -f "{{app_dir}}"
- hosts: prod-host
  become: yes
  tasks:
  - name: install packages-prod-host
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    with_items:
      "{{packages-build-host[0] [1]}}"
  - name: copy tomcat-install.sh
    script: ./tomcat-install.sh
  - name: copy unit file
    src: ./tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  - name: Start and enable tomcat
  systemd:
    name: tomcat
    daemon_reload: yes
    state: started
    enabled: yes